fix the duplicate import file
Evezerest/AutoLabel pull request #11
Opened 2020-11-06 07:46 UTC by BeyondYourself

Fixed the problem of repeatedly importing images by clicking on the same image or thumbnail

2020-11-06 13:31 UTC, Evezerest requested changes

2020-11-06 13:31 UTC, Evezerest commented on AutoLabel.py
> +        if currIndex < len(self.mImgList)-1:
A bug appears when I double click the last item

2020-11-06 13:31 UTC, Evezerest commented on AutoLabel.py
> -
Keep these codes first in case we need later

2020-11-09 05:03 UTC, BeyondYourself commented
当前py没有直接用到PYQT，至于以后兼容的问题，建议前后端分离

2020-11-10 08:58 UTC, merged